version: "3.4"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    user: root
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysqldb:/var/lib/mysql:rw


  springapp:
    image: samarbelhadj/achat
    container_name: springapp
    restart: on-failure
    volumes:
      - .m2:/root/.m2
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
      
      
  angularapp:
   image: samarbelhadj/achat-angular
   container_name: angularapp
   restart: on-failure
   ports:
     - 4200:80
   links:
     - springapp
   depends_on:
     - springapp
  


volumes:
  mysqldb: { }
