version: "3.4"

services:
  mysql-container4:
    container_name: mysql-container4
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    restart: always
    volumes:
      - mysql-container4:/var/lib/mysql:rw
    image: 'mysql:latest'
  achat-backend:
    depends_on:
      - mysql-container4
    container_name: achat-backend
    ports:
      - '8089:8089'
    image: eyatrifii/achat-backend

volumes:
  mysql-container4: { }