
version: "3.4"

services:
  mysql-container3:
    container_name: mysql-container3
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    restart: always
    volumes:
      - /home/mysql/data:/var/lib/mysql:rw
    image: 'mysql:latest'
  achatback:
    container_name: achatback
    ports:
      - '8089:8089'
    image: achatback

volumes:
  mysql_data_container3: {}